version: 0.2

phases:
  install:
    commands:
      # Fetch the unique SHA for tagging Docker images
      - SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 300903264828.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo Build started for commit $SHA
      - echo Building the Docker image...
      - docker build -t lambda-from-container-image:$SHA .
      - docker tag lambda-from-container-image:$SHA 300903264828.dkr.ecr.us-east-2.amazonaws.com/lambda-from-container-image:$SHA

  post_build:
    commands:
      - echo Build completed for commit $SHA
      - echo Pushing the Docker image to ECR...
      - docker push 300903264828.dkr.ecr.us-east-2.amazonaws.com/lambda-from-container-image:$SHA

      # Check if the Lambda function exists to update or create it
      - echo "Running the custom shell script..."
      - chmod +x scripts/create_or_update_lambda_function.sh   # Ensure the script is executable
      - ./scripts/create_or_update_lambda_function.sh     
